name: Zalo Mini App
run-name: ${{ github.event_name == 'schedule' && '✨ Refresh token' || '🚀 Deploy' }}

concurrency: zalo-mini-app

on:
  push:
    branches:
      - main
      - "feat/**"
  pull_request:
    branches:
      - main
      - "feat/**"
  schedule:
    - cron: "0 0 * * *"

jobs:
  refresh_token:
    if: ${{ github.event_name == 'schedule' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: "npm"
      - run: npx zmp-developer-token login 665783553055575149 HpYP1w-ZArv0CfGAgQqgNaGnaWUgjaDO0rkXP927RK9bTDGQrOSqHqbPzNlMXJLHPc-CNkhrTcX4E8yfxULFSdDuztFnvX9LN7wlRRIrPsawQzrhjV8pToOixoEji2SW4bNhV8kB2sHcTB5Ap9vnTJb_g5M3faaF5qQT9ggEKG4j5UyVmkmAHNW3nrxPwG1cRJ3OEzlrEYTjRUa8xRuaFLP4vHdzXWH2L62xUxs-1MyTM-rde9WG9an0_I3EsJ00M0NKNRBzE68B4e5CaVf0LmGwh7UVuKrA9G3qSuNBBZ8V9iiwXFKd13uUraMWq0XXJY7gVidQ0rHh2xXV-ivxMdrNg7p4pafVM2om1k7cTZvL6imqtjm44LFOgOjigxycM0 >> $GITHUB_ENV
      - uses: hmanzur/actions-set-secret@v2.0.0
        with:
          name: "ZALO_ACCESS_TOKEN"
          value: ${{ env.NEW_ACCESS_TOKEN }}
          token: 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
      - uses: hmanzur/actions-set-secret@v2.0.0
        with:
          name: "ZALO_REFRESH_TOKEN"
          value: ${{ env.NEW_REFRESH_TOKEN }}
          token: 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
      - name: Report
        run: |
          echo "### Token renewal success! :sparkles:" >> $GITHUB_STEP_SUMMARY

  deploy:
    if: ${{ github.event_name == 'push' || github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        mini-app-id: ["665783553055575149"]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: "npm"
      - run: npm install
      - run: npm install -g zmp-cli
      - run: npx zmp-developer-token deploy ${{ matrix.mini-app-id }}
        env:
          NEW_ACCESS_TOKEN: KBcHMG3SgNe5wdfPpoDQ HpYP1w-ZArv0CfGAgQqgNaGnaWUgjaDO0rkXP927RK9bTDGQrOSqHqbPzNlMXJLHPc-CNkhrTcX4E8yfxULFSdDuztFnvX9LN7wlRRIrPsawQzrhjV8pToOixoEji2SW4bNhV8kB2sHcTB5Ap9vnTJb_g5M3faaF5qQT9ggEKG4j5UyVmkmAHNW3nrxPwG1cRJ3OEzlrEYTjRUa8xRuaFLP4vHdzXWH2L62xUxs-1MyTM-rde9WG9an0_I3EsJ00M0NKNRBzE68B4e5CaVf0LmGwh7UVuKrA9G3qSuNBBZ8V9iiwXFKd13uUraMWq0XXJY7gVidQ0rHh2xXV-ivxMdrNg7p4pafVM2om1k7cTZvL6imqtjm44LFOgOjigxycM0
