name: Zalo Mini App
run-name: ${{ github.event_name == 'schedule' && '✨ Refresh token' || '🚀 Deploy' }}

concurrency: zalo-mini-app

on:
  push:
    branches:
      - main
      - "feat/**"
  pull_request:
    branches:
      - main
      - "feat/**"
  schedule:
    - cron: "0 0 * * *"

jobs:
  refresh_token:
    if: ${{ github.event_name == 'schedule' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: "npm"
      - run: npx zmp-developer-token login 4302957848165855356 KBcHMG3SgNe5wdfPpoDQ QgUY7chVf3XjhQyJRD6bE6ckgHvlok0rCUkPLrd5xNOspRaiPEtMT3hFfp5blDjM4hwe8HF3ybSNf9XsVutoBWQqeGXwdwzuAxEe34tDmYmOjxbGOwlpRWk--0z2dF5pCEAq4qVwnd0LwiesRyN1L3synt1Lpua99-lxAcR-ebqVv-mdGjhc01RzbMfUylqpMi2MI0Fdq35ovjz08ystOahU_5mjtViYLCxmOplGkq8xmxK2HCFjTZN-WZzDyiT8CO6y2tZvwd8Nof0B5TdPMqFahnaRdEfLUQUD972cqNPtj9ugCvljMtkKkma5fDnURTkjAYdKzLylyBy-9-BwHqNfyY4Co8HHLTN_Bp1AFnDkmwa- >> $GITHUB_ENV
      - uses: hmanzur/actions-set-secret@v2.0.0
        with:
          name: "ZALO_ACCESS_TOKEN"
          value: ${{ env.NEW_ACCESS_TOKEN }}
          token: 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
      - uses: hmanzur/actions-set-secret@v2.0.0
        with:
          name: "ZALO_REFRESH_TOKEN"
          value: ${{ env.NEW_REFRESH_TOKEN }}
          token: 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
      - name: Report
        run: |
          echo "### Token renewal success! :sparkles:" >> $GITHUB_STEP_SUMMARY

  deploy:
    if: ${{ github.event_name == 'push' || github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        mini-app-id: ["665783553055575149"]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: "npm"
      - run: npm install
      - run: npm install -g zmp-cli
      - run: npx zmp-developer-token deploy ${{ matrix.mini-app-id }}
        env:
          NEW_ACCESS_TOKEN: HDZNI4gBYmv3qjf5J8MA3aVHt4XFdemE1wkpJqk-a7KcfwHeS9FnBYF4s1fpzuqg6UUW4KtKZ002mPuHSDMvBoJdZcb-zBvKAihhHdwPprrvpln1CiVV15_yu2rOxSO68S7l6rhdlGa2qUeWNkF535YmxmmSdhCRTh2xCH24aI4QWRysSj6LDot-m7TghEDj09tAK6gRwsaXpUfuH_cxN0pyba5T-h
