name: Zalo Mini App
run-name: ${{ github.event_name == 'schedule' && '✨ Refresh token' || '🚀 Deploy' }}

concurrency: zalo-mini-app

on:
  push:
    branches:
      - main
      - "feat/**"
  pull_request:
    branches:
      - main
      - "feat/**"
  schedule:
    - cron: "0 0 * * *"

jobs:
  refresh_token:
    if: ${{ github.event_name == 'schedule' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: "npm"
      - run: npx zmp-developer-token login  665783553055575149 KBcHMG3SgNe5wdfPpoDQ CZ5bG4rVG7OrEsXDIr51TZ4uRa18IZjmDdXbFanEJMSoTc0kBNKs6IrFRNXIOJDDKaXXVIHRJYGQNmDmO6fQ0KPdTtDhJrD67NKA4XvvHbWaH6qMKrasOLXj6HDGMLGYRLy0K4zJIJnrU1DU2s0yB2Pr46SnM400IbS5Cr9d8KLyNd0HH60w84TMLtauI0CDCo9UIGyOUWqoAnS_AK1VL5Ck1HinD54j9bmL6nnjHd1g1XShP3zR66TKCInyUtvvHN1ND7D_1aH655iA9249VY8nR3O2DHmD5JnV8m0NS4SABGfmDIPWDK8G3bf8V5mQO6uOAW9GPryWD08wEYyhQpuGVHyL1Lbl7W4ADLTFN1m3IKDDS0 >> $GITHUB_ENV
      - uses: hmanzur/actions-set-secret@v2.0.0
        with:
          name: "ZALO_ACCESS_TOKEN"
          value: ${{ env.NEW_ACCESS_TOKEN }}
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
      - uses: hmanzur/actions-set-secret@v2.0.0
        with:
          name: "ZALO_REFRESH_TOKEN"
          value: ${{ env.NEW_REFRESH_TOKEN }}
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
      - name: Report
        run: |
          echo "### Token renewal success! :sparkles:" >> $GITHUB_STEP_SUMMARY

  deploy:
    if: ${{ github.event_name == 'push' || github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        mini-app-id: ["665783553055575149"]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: "npm"
      - run: npm install
      - run: npm install -g zmp-cli
      - run: npx zmp-developer-token deploy ${{ matrix.mini-app-id }}
        env:
          NEW_ACCESS_TOKEN: ${{ secrets.ZALO_ACCESS_TOKEN }}
      - name: Report
        run: |
          echo "### Deployment success! :rocket:" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY # this is a blank line
          echo "View your deployment result: [Version Management](https://mini.zalo.me/miniapp/${{ matrix.mini-app-id }}/versions)" >> $GITHUB_STEP_SUMMARY
