name: Zalo Mini App
run-name: 🚀 Deploy

concurrency: zalo-mini-app

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mini-app-id: ["665783553055575149"]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: "npm"
      - run: npm install
      - run: npm install -g zmp-cli
      - run: npx zmp-developer-token deploy ${{ matrix.mini-app-id }}
        env:
          NEW_ACCESS_TOKEN: ${{ secrets.ZALO_ACCESS_TOKEN }}
      - name: Report
        run: |
          echo "### Deployment success! :rocket:" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "View your deployment result: [Version Management](https://mini.zalo.me/miniapp/${{ matrix.mini-app-id }}/versions)" >> $GITHUB_STEP_SUMMARY
